# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"

  config.vm.network "private_network", ip: "192.168.33.11"
  config.vm.network "forwarded_port", guest: 22, host: 3333, host_ip: "127.0.0.1", id: "ssh"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.name = "ubuntu-dev"
    vb.memory = "4096"
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
	  vb.customize ["modifyvm", :id,  "--natdnshostresolver1", "on"]
  end
end